In [1]:
import numpy as np
import math
from sklearn.preprocessing import StandardScaler

In [2]:
X = np.array([[3.0,2.0,100.0],[4.0,1.0,75.0],[2.0,1.0,40.0]]) # float for preventing StandardScaler() varnings
print(X)

[[  3.   2. 100.]
 [  4.   1.  75.]
 [  2.   1.  40.]]


In [13]:
def standardize_features(dataset):
    result = np.zeros(dataset.shape)
    mean = np.mean(dataset, axis = 0)        
    temp = np.power(dataset- mean ,2)        
    sigma = np.sqrt(temp.sum(axis = 0) / len(dataset) )    
    result = np.round((dataset - mean) / sigma, 3)      

    return result

In [14]:
scaler_X =np.round(StandardScaler().fit_transform(X),3)
scaler_X

array([[ 0.   ,  1.414,  1.151],
       [ 1.225, -0.707,  0.135],
       [-1.225, -0.707, -1.287]])

In [15]:
nex_X = standardize_features(X)
nex_X

array([[ 0.   ,  1.414,  1.151],
       [ 1.225, -0.707,  0.135],
       [-1.225, -0.707, -1.287]])